WebOfficePreview/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebOfficePreview.Models;
using Component_OfficePreview.Data;
using Microsoft.AspNetCore.Http;
using Component_OfficePreview.Entities;
using WebOfficePreview.Models.ApiViewModels;
using WebOfficePreview.Services;
using Component_OfficePreview;

namespace WebOfficePreview.Controllers
{
    public class ApiController : Controller
    {
        public readonly ApplicationDbContext _context;
        public readonly FileUploader _fileUploader;

        public ApiController(ApplicationDbContext context, FileUploader fileUploader)
        {
            _context = context;
            _fileUploader = fileUploader;
        }

        public IActionResult Index()
        {
            return View();
        }

        public JsonResult Get(string key, int FileId)
        {
            UserDb user = _context.Users.FirstOrDefault(x => x.ApiHash == key);

            if (user is null)
            {
                return GetViewModel(FileId, (int)FileUploaderStatus.ErrorRequireAuthentication);
            }

            FileDb file = _context.Files.FirstOrDefault(x => x.Id == FileId && x.UserId == user.UserId);

            if(file is null)
            {
                return GetViewModel(FileId, (int)FileUploaderStatus.ErrorNotFound);
            }

            return GetViewModel(FileId, (int)file.Status);
        }

        public async Task<JsonResult> Upload(string key, IFormFile file)
        {
            UserDb user = _context.Users.FirstOrDefault(x => x.ApiHash == key);

            if(user is null)
            {
                return Json(new UploadViewModel
                {
                    Status = (int)FileUploaderStatus.ErrorRequireAuthentication
                });
            }

            FileUplaoderResult UploadResult = await _fileUploader.Upload(file, user.UserId);

            return Json(new UploadViewModel
            {
                FileId = UploadResult.FileId,
                Status = (int)UploadResult.Status
            });
        }

        #region -- Helpers

        private JsonResult GetViewModel(int FileId, int Status)
        {
            return Json(new GetViewModel
            {
                FileId = FileId,
                Status = Status
            });
        }

        #endregion

    }
}

WebOfficePreview/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebOfficePreview.Models;
using Component_OfficePreview.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Http;
using Component_OfficePreview.Entities;
using Microsoft.AspNetCore.Authorization;
using Component_OfficePreview;
using Microsoft.AspNetCore.Mvc.Filters;
using WebOfficePreview.Services;

namespace WebOfficePreview.Controllers
{
    public class HomeController : _Controller
    {
        public readonly IHostingEnvironment _environment;
        public readonly ApplicationDbContext _context;
        public readonly FileUploader _fileUploader;

        public HomeController(IHostingEnvironment environment, ApplicationDbContext context, FileUploader fileUploader)
        {
            _environment = environment;
            _context = context;
            _fileUploader = fileUploader;
        }

        [Authorize]
        public IActionResult Cabinet(int? DeleteFileId)
        {
            int userId = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "UserId").Value);

            #region -- Remove file

            if (DeleteFileId != null)
            {
                FileDb file = _context.Files.FirstOrDefault(x => x.UserId == userId && x.Id == DeleteFileId);

                if (file is null)
                {
                    ViewBag.Notify.Add("danger", "Файл не найден, либо уже удален");
                }
                else
                {
                    string destFile = Path.Combine(_environment.WebRootPath + @"\Files\", file.Hash + file.Extension);
                    string xpsFile = Path.Combine(_environment.WebRootPath + @"\ConvertedFiles\", file.Hash + ".xps");

                    if (System.IO.File.Exists(destFile))
                    {
                        System.IO.File.Delete(destFile);
                    }

                    if (System.IO.File.Exists(xpsFile))
                    {
                        System.IO.File.Delete(xpsFile);
                    }

                    for (int i = 0; i < file.Pages; i++)
                    {
                        string pageFile = Path.Combine(_environment.WebRootPath, "ConvertedImages", file.Hash + "_" + i.ToString() + ".jpg");

                        if (System.IO.File.Exists(pageFile))
                        {
                            System.IO.File.Delete(pageFile);
                        }
                    }

                    _context.Files.Remove(file);
                    _context.SaveChanges();

                    ViewBag.Notify.Add("success", "Файл успешно удален");
                }
            }

            #endregion

            List<FileDb> files = _context.Files.Where(x => x.UserId == userId).OrderByDescending(x => x.DateUpload).ToList();

            return View(files);
        }

        [Route("Show/{FileHash}")]
        public IActionResult Show(string FileHash)
        {
            FileDb file = _context.Files.FirstOrDefault(x => x.Hash == FileHash);

            if (file is null)
            {
                TempData["danger"] = "Ошибка! Такой файл не найден.";

                return RedirectToAction("Index");
            }

            return View(file);
        }

        public IActionResult Index()
        {
            if(User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Cabinet");
            }

            return View(_context.Files.ToList());
        }

        public IActionResult Demo()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            int userId = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "UserId").Value);

            FileUplaoderResult UploadResult = await _fileUploader.Upload(uploadedFile, userId);

            if(UploadResult.Status == FileUploaderStatus.ErrorNoUpload)
            {
                TempData["danger"] = "Ошибка! Вы не выбрали файл.";
            }

            if (UploadResult.Status == FileUploaderStatus.ErrorBadFormat)
            {
                TempData["danger"] = "Ошибка! К загрузке разрешены только файлы Word, Excel и PowerPoint.";
            }

            if (UploadResult.Status == FileUploaderStatus.ErrorTooLarge)
            {
                TempData["danger"] = "Ошибка! Размер файла превышает 10 Мб.";
            }

            if( !TempData.ContainsKey("danger"))
            {
                TempData["success"] = "Файл добавлен в очередь на обработку.";
            }

            return RedirectToAction("Index");
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebOfficePreview/Views/Home/Cabinet.cshtml
@model List<FileDb>

@{
    ViewData["Title"] = "Личный кабинет";
}

<div class="jumbotron jumbotron-fluid">
    <div class="container text-center" >
        <h3>Выберите файл для загрузки</h3>
        <form asp-controller="Home" asp-action="AddFile" method="post" enctype="multipart/form-data">
            <input type="file" name="uploadedFile" accept=".doc, .docx, .xls, .xlsx, .ppt, .pptx" />
            <input type="submit" value="Загрузить" class="btn btn-primary" />
        </form>
    </div>
</div>

<h3 class="text-center mb-4">Мои файлы</h3>

<table class="table table-hover">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Статус</th>
            <th>Размер файла</th>
            <th>Дата</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var file in Model)
        {
            <tr>
                <td>@file.Name</td>
                <td>@file.Status.GetDisplayName()</td>
                @if (file.Filesize > 1024 * 1024)
                {
                    <td>@Math.Round(file.Filesize / (1024d * 1024), 2) Мб</td>
                }
                else
                {
                    <td>@Math.Round(file.Filesize / 1024d, 2) кб</td>
                }
                <td>@file.DateUpload</td>
                <td>
                    @if (file.Status == FileUploaderStatus.Ok)
                    {
                        <a target="_blank" href="/show/@file.Hash">Открыть</a>
                    }
                    <a href="/Home/Cabinet/?DeleteFileId=@file.Id">Удалить файл</a>
                </td>
            </tr>
        }
    </tbody>
</table>

WebOfficePreview/Views/Home/Demo.cshtml
@{
    ViewData["Title"] = "Демонастрация API";
}

<div class="card">
    <div class="card-header">
        Загрузка файла /Api/Upload
    </div>
    <div class="card-body">
        <form asp-action="Upload" asp-controller="Api" method="post" enctype="multipart/form-data">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Ключ API</label>
                <div class="col-sm-4">
                    <input type="text" name="key" value="" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Файл</label>
                <div class="col-sm-4">
                    <input type="file" name="file" class="form-control" />
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Загрузить</button>
        </form>
    </div>
</div>

<div class="card mt-4">
    <div class="card-header">
        Проверка файла /Api/Get
    </div>
    <div class="card-body">
        <form asp-action="Get" asp-controller="Api" method="post" enctype="multipart/form-data">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Ключ API</label>
                <div class="col-sm-4">
                    <input type="text" name="key" value="" class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">File Id</label>
                <div class="col-sm-4">
                    <input type="text" name="FileId" value="" class="form-control" />
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Проверить</button>
        </form>
    </div>
</div>

WebOfficePreview/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Предпросмотр файлов Office";
}

<div class="container" style="text-align: center;">
    <h2 class="display-4" style="font-size: 3rem">Просматривай файлы Word, Excel и PowerPoint</h2>
    <p class="lead">с устройств без пакета Microsoft Office...</p>
</div>

<div class="row">
    <div class="col" style="text-align: center;">
        <img class="card-img-top" src="~/Images/download.png" style="max-width: 50%;" /><br />
        <div>Загружай</div>
    </div>

    <div class="col" style="text-align: center;">
        <img class="card-img-top" src="~/Images/refresh.png" style="max-width: 50%;" /><br />
        <div>Конвертируй</div>
    </div>

    <div class="col" style="text-align: center;">
        <img class="card-img-top" src="~/Images/list.png" style="max-width: 50%;" /><br />
        <div>Просматривай</div>
    </div>
</div>

<div class="container" style="text-align: center;">
    <br /><br /><br />
    <h2 class="display-5">Просто зарегистрируйся и начни работу!</h2>
    <br /><br />
</div>

WebOfficePreview/Views/Home/Show.cshtml
@model FileDb

@{
    ViewData["Title"] = Model?.Name;
}

<div class="text-center">
    <h3>Файл &laquo;@Model.Name&raquo; от @Model.DateUpload</h3>
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        @for (int i = 1; i <= Model.Pages; i++)
        {
            <li data-target="#carouselExampleIndicators" data-slide-to="@(i-1)" class="@(i == 1 ? "active" :"")" style="background-color: #000"></li>
        }
    </ol>
    <div class="carousel-inner">
        @for (int i = 1; i <= Model.Pages; i++)
        {
            string filename = ("/ConvertedImages/" + Model.Hash + "_" + i.ToString() + ".png");
            var activeClass = (i == 1) ? "active" : "";

            <div class="carousel-item @activeClass">
                <img class="d-block w-100" src="@filename" alt="@i" style="max-width: 1000px" />
            </div>
        }
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>